Class {
	#name : #PluralizeTest,
	#superclass : #TestCase,
	#category : #'SingularizePluralize-Tests'
}

{ #category : #tests }
PluralizeTest >> testPluralOfAlias [
	self assert: 'alias' asPlural equals: 'aliases'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAnalysis [
	self assert: 'analysis' asPlural equals: 'analyses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfArchive [
	self assert: 'archive' asPlural equals: 'archives'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAuditoria [
	self assert: 'auditoria' asPlural equals: 'auditoria'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAuditorium [
	self assert: 'auditorium' asPlural equals: 'auditoria'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAxis [
	self assert: 'axis' asPlural equals: 'axes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBanana [
	self assert: 'banana' asPlural equals: 'bananas'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBeef [
	self assert: 'beef' asPlural equals: 'beef'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBelief [
	self assert: 'belief' asPlural equals: 'beliefs'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBlitz [
	self assert: 'blitz' asPlural equals: 'blitzes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBox [
	self assert: 'box' asPlural equals: 'boxes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBoy [
	self assert: 'boy' asPlural equals: 'boys'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBus [
	self assert: 'bus' asPlural equals: 'buses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfCactus [
	self assert: 'cactus' asPlural equals: 'cacti'
]

{ #category : #tests }
PluralizeTest >> testPluralOfCat [
	self assert: 'cat' asPlural equals: 'cats'
]

{ #category : #tests }
PluralizeTest >> testPluralOfChef [
	self assert: 'chef' asPlural equals: 'chefs'
]

{ #category : #tests }
PluralizeTest >> testPluralOfChief [
	self assert: 'chief' asPlural equals: 'chiefs'
]

{ #category : #tests }
PluralizeTest >> testPluralOfChild [
	self assert: 'child' asPlural equals: 'children'
]

{ #category : #tests }
PluralizeTest >> testPluralOfCity [
	self assert: 'city' asPlural equals: 'cities'
]

{ #category : #tests }
PluralizeTest >> testPluralOfColloquy [
	self assert: 'colloquy' asPlural equals: 'colloquies'
]

{ #category : #tests }
PluralizeTest >> testPluralOfCountry [
	self assert: 'country' asPlural equals: 'countries'
]

{ #category : #tests }
PluralizeTest >> testPluralOfCriterion [
	self assert: 'criterion' asPlural equals: 'criteria'
]

{ #category : #tests }
PluralizeTest >> testPluralOfDatum [
	self assert: 'datum' asPlural equals: 'data'
]

{ #category : #tests }
PluralizeTest >> testPluralOfDeer [
	self assert: 'deer' asPlural equals: 'deer'
]

{ #category : #tests }
PluralizeTest >> testPluralOfDwarf [
	self assert: 'dwarf' asPlural equals: 'dwarves'
]

{ #category : #tests }
PluralizeTest >> testPluralOfEclipsis [
	self assert: 'eclipsis' asPlural equals: 'eclipses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfEllipse [
	self assert: 'ellipse' asPlural equals: 'ellipses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfEntity [
	self assert: 'entity' asPlural equals: 'entities'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFez [
	self assert: 'fez' asPlural equals: 'fezzes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFish [
	self assert: 'fish' asPlural equals: 'fish'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFocus [
	self assert: 'focus' asPlural equals: 'foci'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFolk [
	self assert: 'folk' asPlural equals: 'folk'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFoot [
	self assert: 'foot' asPlural equals: 'feet'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFriend [
	self assert: 'friend' asPlural equals: 'friends'
]

{ #category : #tests }
PluralizeTest >> testPluralOfGas [
	self assert: 'gas' asPlural equals: 'gasses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfGlass [
	self assert: 'glass' asPlural equals: 'glasses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfGoose [
	self assert: 'goose' asPlural equals: 'geese'
]

{ #category : #tests }
PluralizeTest >> testPluralOfHalo [
	self assert: 'halo' asPlural equals: 'halos'
]

{ #category : #tests }
PluralizeTest >> testPluralOfHouse [
	self assert: 'house' asPlural equals: 'houses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfIndex [
	self assert: 'index' asPlural equals: 'indices'
]

{ #category : #tests }
PluralizeTest >> testPluralOfKnife [
	self assert: 'knife' asPlural equals: 'knives'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLady [
	self assert: 'lady' asPlural equals: 'ladies'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLice [
	self assert: 'lice' asPlural equals: 'lice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLouse [
	self assert: 'louse' asPlural equals: 'lice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLunch [
	self assert: 'lunch' asPlural equals: 'lunches'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMan [
	self assert: 'man' asPlural equals: 'men'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMarsh [
	self assert: 'marsh' asPlural equals: 'marshes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMatrix [
	self assert: 'matrix' asPlural equals: 'matrices'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMedium [
	self assert: 'medium' asPlural equals: 'media'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMice [
	self assert: 'mice' asPlural equals: 'mice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMouse [
	self assert: 'mouse' asPlural equals: 'mice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfOctopus [
	self assert: 'octopus' asPlural equals: 'octopi'
]

{ #category : #tests }
PluralizeTest >> testPluralOfOx [
	self assert: 'ox' asPlural equals: 'oxen'
]

{ #category : #tests }
PluralizeTest >> testPluralOfOxen [
	self assert: 'oxen' asPlural equals: 'oxen'
]

{ #category : #tests }
PluralizeTest >> testPluralOfPerson [
	self assert: 'person' asPlural equals: 'people'
]

{ #category : #tests }
PluralizeTest >> testPluralOfPhenomenon [
	self assert: 'phenomenon' asPlural equals: 'phenomena'
]

{ #category : #tests }
PluralizeTest >> testPluralOfPhoto [
	self assert: 'photo' asPlural equals: 'photos'
]

{ #category : #tests }
PluralizeTest >> testPluralOfPiano [
	self assert: 'piano' asPlural equals: 'pianos'
]

{ #category : #tests }
PluralizeTest >> testPluralOfPotato [
	self assert: 'potato' asPlural equals: 'potatoes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfPuppy [
	self assert: 'puppy' asPlural equals: 'puppies'
]

{ #category : #tests }
PluralizeTest >> testPluralOfQuiz [
	self assert: 'quiz' asPlural equals: 'quizzes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfRay [
	self assert: 'ray' asPlural equals: 'rays'
]

{ #category : #tests }
PluralizeTest >> testPluralOfRoof [
	self assert: 'roof' asPlural equals: 'roofs'
]

{ #category : #tests }
PluralizeTest >> testPluralOfSelf [
	self assert: 'self' asPlural equals: 'selves'
]

{ #category : #tests }
PluralizeTest >> testPluralOfSeries [
	self assert: 'series' asPlural equals: 'series'
]

{ #category : #tests }
PluralizeTest >> testPluralOfSheep [
	self assert: 'sheep' asPlural equals: 'sheep'
]

{ #category : #tests }
PluralizeTest >> testPluralOfShoe [
	self assert: 'shoe' asPlural equals: 'shoes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfSpecies [
	self assert: 'species' asPlural equals: 'species'
]

{ #category : #tests }
PluralizeTest >> testPluralOfStatus [
	self assert: 'status' asPlural equals: 'statuses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfTax [
	self assert: 'tax' asPlural equals: 'taxes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfThesis [
	self assert: 'thesis' asPlural equals: 'theses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfTomato [
	self assert: 'tomato' asPlural equals: 'tomatoes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfTooth [
	self assert: 'tooth' asPlural equals: 'teeth'
]

{ #category : #tests }
PluralizeTest >> testPluralOfTruss [
	self assert: 'truss' asPlural equals: 'trusses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfVertex [
	self assert: 'vertex' asPlural equals: 'vertices'
]

{ #category : #tests }
PluralizeTest >> testPluralOfVirus [
	self assert: 'virus' asPlural equals: 'viri'
]

{ #category : #tests }
PluralizeTest >> testPluralOfVolcano [
	self assert: 'volcano' asPlural equals: 'volcanos'
]

{ #category : #tests }
PluralizeTest >> testPluralOfWife [
	self assert: 'wife' asPlural equals: 'wives'
]

{ #category : #tests }
PluralizeTest >> testPluralOfWolf [
	self assert: 'wolf' asPlural equals: 'wolves'
]

{ #category : #tests }
PluralizeTest >> testPluralOfWoman [
	self assert: 'woman' asPlural equals: 'women'
]
