Class {
	#name : #SingularizeTest,
	#superclass : #TestCase,
	#category : #'SingularizePluralize-Tests'
}

{ #category : #tests }
SingularizeTest >> testSingularOfAliases [
	self assert: 'aliases' asSingular equals: 'alias'
]

{ #category : #tests }
SingularizeTest >> testSingularOfAnalyses [
	self assert: 'analyses' asSingular equals: 'analysis'
]

{ #category : #tests }
SingularizeTest >> testSingularOfArchives [
	self assert: 'archives' asSingular equals: 'archive'
]

{ #category : #tests }
SingularizeTest >> testSingularOfAssertions [
	self assert: 'assertions' asSingular equals: 'assertion'
]

{ #category : #tests }
SingularizeTest >> testSingularOfAuditoria [
	self assert: 'auditoria' asSingular equals: 'auditorium'
]

{ #category : #tests }
SingularizeTest >> testSingularOfAuditorium [
	self assert: 'auditorium' asSingular equals: 'auditorium'
]

{ #category : #tests }
SingularizeTest >> testSingularOfAxes [
	self assert: 'axes' asSingular equals: 'axis'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBananas [
	self assert: 'bananas' asSingular equals: 'banana'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBeef [
	self assert: 'beef' asSingular equals: 'beef'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBeliefs [
	self assert: 'beliefs' asSingular equals: 'belief'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBlitzes [
	self assert: 'blitzes' asSingular equals: 'blitz'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBoxes [
	self assert: 'boxes' asSingular equals: 'box'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBoys [
	self assert: 'boys' asSingular equals: 'boy'
]

{ #category : #tests }
SingularizeTest >> testSingularOfBuses [
	self assert: 'buses' asSingular equals: 'bus'
]

{ #category : #tests }
SingularizeTest >> testSingularOfCacti [
	self assert: 'cacti' asSingular equals: 'cactus'
]

{ #category : #tests }
SingularizeTest >> testSingularOfCats [
	self assert: 'cats' asSingular equals: 'cat'
]

{ #category : #tests }
SingularizeTest >> testSingularOfChefs [
	self assert: 'chefs' asSingular equals: 'chef'
]

{ #category : #tests }
SingularizeTest >> testSingularOfChiefs [
	self assert: 'chiefs' asSingular equals: 'chief'
]

{ #category : #tests }
SingularizeTest >> testSingularOfChildren [
	self assert: 'children' asSingular equals: 'child'
]

{ #category : #tests }
SingularizeTest >> testSingularOfCities [
	self assert: 'cities' asSingular equals: 'city'
]

{ #category : #tests }
SingularizeTest >> testSingularOfColloquies [
	self assert: 'colloquies' asSingular equals: 'colloquy'
]

{ #category : #tests }
SingularizeTest >> testSingularOfConnections [
	self assert: 'connections' asSingular equals: 'connection'
]

{ #category : #tests }
SingularizeTest >> testSingularOfCountries [
	self assert: 'countries' asSingular equals: 'country'
]

{ #category : #tests }
SingularizeTest >> testSingularOfCriteria [
	self assert: 'criteria' asSingular equals: 'criterion'
]

{ #category : #tests }
SingularizeTest >> testSingularOfData [
	self assert: 'data' asSingular equals: 'datum'
]

{ #category : #tests }
SingularizeTest >> testSingularOfDeer [
	self assert: 'deer' asSingular equals: 'deer'
]

{ #category : #tests }
SingularizeTest >> testSingularOfDwarves [
	self assert: 'dwarves' asSingular equals: 'dwarf'
]

{ #category : #tests }
SingularizeTest >> testSingularOfEllipses [
	self assert: 'ellipses' asSingular equals: 'ellipse'
]

{ #category : #tests }
SingularizeTest >> testSingularOfEntities [
	self assert: 'entities' asSingular equals: 'entity'
]

{ #category : #tests }
SingularizeTest >> testSingularOfFeet [
	self assert: 'feet' asSingular equals: 'foot'
]

{ #category : #tests }
SingularizeTest >> testSingularOfFezzes [
	self assert: 'fezzes' asSingular equals: 'fez'
]

{ #category : #tests }
SingularizeTest >> testSingularOfFish [
	self assert: 'fish' asSingular equals: 'fish'
]

{ #category : #tests }
SingularizeTest >> testSingularOfFoci [
	self assert: 'foci' asSingular equals: 'focus'
]

{ #category : #tests }
SingularizeTest >> testSingularOfFolk [
	self assert: 'folk' asSingular equals: 'folk'
]

{ #category : #tests }
SingularizeTest >> testSingularOfFriends [
	self assert: 'friends' asSingular equals: 'friend'
]

{ #category : #tests }
SingularizeTest >> testSingularOfGasses [
	self assert: 'gasses' asSingular equals: 'gas'
]

{ #category : #tests }
SingularizeTest >> testSingularOfGeese [
	self assert: 'geese' asSingular equals: 'goose'
]

{ #category : #tests }
SingularizeTest >> testSingularOfGlasses [
	self assert: 'glasses' asSingular equals: 'glass'
]

{ #category : #tests }
SingularizeTest >> testSingularOfHalos [
	self assert: 'halos' asSingular equals: 'halo'
]

{ #category : #tests }
SingularizeTest >> testSingularOfHouses [
	self assert: 'houses' asSingular equals: 'house'
]

{ #category : #tests }
SingularizeTest >> testSingularOfIndices [
	self assert: 'indices' asSingular equals: 'index'
]

{ #category : #tests }
SingularizeTest >> testSingularOfKnives [
	self assert: 'knives' asSingular equals: 'knife'
]

{ #category : #tests }
SingularizeTest >> testSingularOfLadies [
	self assert: 'ladies' asSingular equals: 'lady'
]

{ #category : #tests }
SingularizeTest >> testSingularOfLice [
	self assert: 'lice' asSingular equals: 'louse'
]

{ #category : #tests }
SingularizeTest >> testSingularOfLocations [
	self assert: 'locations' asSingular equals: 'location'
]

{ #category : #tests }
SingularizeTest >> testSingularOfLouse [
	self assert: 'louse' asSingular equals: 'louse'
]

{ #category : #tests }
SingularizeTest >> testSingularOfLunches [
	self assert: 'lunches' asSingular equals: 'lunch'
]

{ #category : #tests }
SingularizeTest >> testSingularOfMarshes [
	self assert: 'marshes' asSingular equals: 'marsh'
]

{ #category : #tests }
SingularizeTest >> testSingularOfMatrices [
	self assert: 'matrices' asSingular equals: 'matrix'
]

{ #category : #tests }
SingularizeTest >> testSingularOfMedia [
	self assert: 'media' asSingular equals: 'medium'
]

{ #category : #tests }
SingularizeTest >> testSingularOfMen [
	self assert: 'men' asSingular equals: 'man'
]

{ #category : #tests }
SingularizeTest >> testSingularOfMice [
	self assert: 'mice' asSingular equals: 'mouse'
]

{ #category : #tests }
SingularizeTest >> testSingularOfMouse [
	self assert: 'mouse' asSingular equals: 'mouse'
]

{ #category : #tests }
SingularizeTest >> testSingularOfOctopi [
	self assert: 'octopi' asSingular equals: 'octopus'
]

{ #category : #tests }
SingularizeTest >> testSingularOfOx [
	self assert: 'ox' asSingular equals: 'ox'
]

{ #category : #tests }
SingularizeTest >> testSingularOfOxen [
	self assert: 'oxen' asSingular equals: 'ox'
]

{ #category : #tests }
SingularizeTest >> testSingularOfPeople [
	self assert: 'people' asSingular equals: 'person'
]

{ #category : #tests }
SingularizeTest >> testSingularOfPhenomena [
	self assert: 'phenomena' asSingular equals: 'phenomenon'
]

{ #category : #tests }
SingularizeTest >> testSingularOfPhotos [
	self assert: 'photos' asSingular equals: 'photo'
]

{ #category : #tests }
SingularizeTest >> testSingularOfPianos [
	self assert: 'pianos' asSingular equals: 'piano'
]

{ #category : #tests }
SingularizeTest >> testSingularOfPotatoes [
	self assert: 'potatoes' asSingular equals: 'potato'
]

{ #category : #tests }
SingularizeTest >> testSingularOfPuppies [
	self assert: 'puppies' asSingular equals: 'puppy'
]

{ #category : #tests }
SingularizeTest >> testSingularOfQuizzes [
	self assert: 'quizzes' asSingular equals: 'quiz'
]

{ #category : #tests }
SingularizeTest >> testSingularOfRays [
	self assert: 'rays' asSingular equals: 'ray'
]

{ #category : #tests }
SingularizeTest >> testSingularOfRoofs [
	self assert: 'roofs' asSingular equals: 'roof'
]

{ #category : #tests }
SingularizeTest >> testSingularOfSelves [
	self assert: 'selves' asSingular equals: 'self'
]

{ #category : #tests }
SingularizeTest >> testSingularOfSeries [
	self assert: 'series' asSingular equals: 'series'
]

{ #category : #tests }
SingularizeTest >> testSingularOfSheep [
	self assert: 'sheep' asSingular equals: 'sheep'
]

{ #category : #tests }
SingularizeTest >> testSingularOfShoes [
	self assert: 'shoes' asSingular equals: 'shoe'
]

{ #category : #tests }
SingularizeTest >> testSingularOfSpecies [
	self assert: 'species' asSingular equals: 'species'
]

{ #category : #tests }
SingularizeTest >> testSingularOfStatuses [
	self assert: 'statuses' asSingular equals: 'status'
]

{ #category : #tests }
SingularizeTest >> testSingularOfTaxes [
	self assert: 'taxes' asSingular equals: 'tax'
]

{ #category : #tests }
SingularizeTest >> testSingularOfTeeth [
	self assert: 'teeth' asSingular equals: 'tooth'
]

{ #category : #tests }
SingularizeTest >> testSingularOfTheses [
	self assert: 'theses' asSingular equals: 'thesis'
]

{ #category : #tests }
SingularizeTest >> testSingularOfTomatoes [
	self assert: 'tomatoes' asSingular equals: 'tomato'
]

{ #category : #tests }
SingularizeTest >> testSingularOfTrusses [
	self assert: 'trusses' asSingular equals: 'truss'
]

{ #category : #tests }
SingularizeTest >> testSingularOfVertices [
	self assert: 'vertices' asSingular equals: 'vertex'
]

{ #category : #tests }
SingularizeTest >> testSingularOfViri [
	self assert: 'viri' asSingular equals: 'virus'
]

{ #category : #tests }
SingularizeTest >> testSingularOfVolcanoes [
	self assert: 'volcanoes' asSingular equals: 'volcano'
]

{ #category : #tests }
SingularizeTest >> testSingularOfVolcanos [
	self assert: 'volcanos' asSingular equals: 'volcano'
]

{ #category : #tests }
SingularizeTest >> testSingularOfWives [
	self assert: 'wives' asSingular equals: 'wife'
]

{ #category : #tests }
SingularizeTest >> testSingularOfWolves [
	self assert: 'wolves' asSingular equals: 'wolf'
]

{ #category : #tests }
SingularizeTest >> testSingularOfWomen [
	self assert: 'women' asSingular equals: 'woman'
]
