Class {
	#name : #PluralizeTest,
	#superclass : #TestCase,
	#category : #'SingularizePluralize-Tests'
}

{ #category : #tests }
PluralizeTest >> testPluralOfAlias [
	self assert: 'alias' asPlural equals: 'aliases'
]

{ #category : #tests }
PluralizeTest >> testPluralOfArchive [
	self assert: 'archieve' asPlural equals: 'archieves'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAuditoria [
	self assert: 'auditoria' asPlural equals: 'auditoria'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAuditorium [
	self assert: 'auditorium' asPlural equals: 'auditoria'
]

{ #category : #tests }
PluralizeTest >> testPluralOfAxis [
	self assert: 'axis' asPlural equals: 'axes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBanana [
	self assert: 'banana' asPlural equals: 'bananas'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBeef [
	self assert: 'beef' asPlural equals: 'beef'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBox [
	self assert: 'box' asPlural equals: 'boxes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfBus [
	self assert: 'bus' asPlural equals: 'buses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfChild [
	self assert: 'child' asPlural equals: 'children'
]

{ #category : #tests }
PluralizeTest >> testPluralOfColloquy [
	self assert: 'colloquy' asPlural equals: 'colloquies'
]

{ #category : #tests }
PluralizeTest >> testPluralOfCountry [
	self assert: 'country' asPlural equals: 'countries'
]

{ #category : #tests }
PluralizeTest >> testPluralOfDatum [
	self assert: 'datum' asPlural equals: 'data'
]

{ #category : #tests }
PluralizeTest >> testPluralOfDwarf [
	self assert: 'dwarf' asPlural equals: 'dwarves'
]

{ #category : #tests }
PluralizeTest >> testPluralOfEntity [
	self assert: 'entity' asPlural equals: 'entities'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFolk [
	self assert: 'folk' asPlural equals: 'folk'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFoot [
	self assert: 'foot' asPlural equals: 'feet'
]

{ #category : #tests }
PluralizeTest >> testPluralOfFriend [
	self assert: 'friend' asPlural equals: 'friends'
]

{ #category : #tests }
PluralizeTest >> testPluralOfGlass [
	self assert: 'glass' asPlural equals: 'glasses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfIndex [
	self assert: 'index' asPlural equals: 'indices'
]

{ #category : #tests }
PluralizeTest >> testPluralOfKnife [
	self assert: 'knife' asPlural equals: 'knives'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLady [
	self assert: 'lady' asPlural equals: 'ladies'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLice [
	self assert: 'lice' asPlural equals: 'lice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfLouse [
	self assert: 'louse' asPlural equals: 'lice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMan [
	self assert: 'man' asPlural equals: 'men'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMatrix [
	self assert: 'matrix' asPlural equals: 'matrices'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMedium [
	self assert: 'medium' asPlural equals: 'media'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMice [
	self assert: 'mice' asPlural equals: 'mice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfMouse [
	self assert: 'mouse' asPlural equals: 'mice'
]

{ #category : #tests }
PluralizeTest >> testPluralOfOctopus [
	self assert: 'octopus' asPlural equals: 'octopi'
]

{ #category : #tests }
PluralizeTest >> testPluralOfOx [
	self assert: 'ox' asPlural equals: 'oxen'
]

{ #category : #tests }
PluralizeTest >> testPluralOfOxen [
	self assert: 'oxen' asPlural equals: 'oxen'
]

{ #category : #tests }
PluralizeTest >> testPluralOfQuiz [
	self assert: 'quiz' asPlural equals: 'quizzes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfSelf [
	self assert: 'self' asPlural equals: 'selves'
]

{ #category : #tests }
PluralizeTest >> testPluralOfSheep [
	self assert: 'sheep' asPlural equals: 'sheep'
]

{ #category : #tests }
PluralizeTest >> testPluralOfShoe [
	self assert: 'shoe' asPlural equals: 'shoes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfStatus [
	self assert: 'status' asPlural equals: 'statuses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfThesis [
	self assert: 'thesis' asPlural equals: 'theses'
]

{ #category : #tests }
PluralizeTest >> testPluralOfTomato [
	self assert: 'tomato' asPlural equals: 'tomatoes'
]

{ #category : #tests }
PluralizeTest >> testPluralOfVertex [
	self assert: 'vertex' asPlural equals: 'vertices'
]

{ #category : #tests }
PluralizeTest >> testPluralOfVirus [
	self assert: 'virus' asPlural equals: 'viri'
]

{ #category : #tests }
PluralizeTest >> testPluralOfWife [
	self assert: 'wife' asPlural equals: 'wives'
]

{ #category : #tests }
PluralizeTest >> testPluralOfWoman [
	self assert: 'woman' asPlural equals: 'women'
]
